### ISSUE TITLE
add the option to smooth the sprites 

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#1]
<img width="594" alt="alias-no-alias" src="https://cloud.githubusercontent.com/assets/5557196/11931312/d05850fc-a7eb-11e5-991b-9747e3c705ca.png">

That's your example inside my game. Left as it is now and right with the sprites of the SpriterGroup smoothed.

It looks like the phaser sprites have the smoothed property false by default. Animations doesn't look well without smoothing.

It would be better if there was a "smoothed" boolean in the Spriter.SpriterGroup constructor. What do you think?

**Comment by SBCGames** [comment]
Phaser.Sprites are smoothed by default (see \src\gameobjects\components\Smoothed.js). Make sure you are not setting antialias off on Game or Stage level.

**Comment by enriqueto** [comment]
you are right, I was creating the game with the antialias parameter to false.
