### ISSUE TITLE
I can't make it work :(

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#10]
Hi Tom,

I'm afraid I can't make it work. There are 3 animations called "idle", "disappointed" and happy. As you suggested I told TP not to use ".png", folders and rotated textures. I'm used the xml output of Spriter as you said you do.

[Texture atlas png](https://dl.dropboxusercontent.com/u/17484152/client.png)
[Texture atlas json](https://dl.dropboxusercontent.com/u/17484152/client.json)
[Spriter XML](https://dl.dropboxusercontent.com/u/17484152/cliente_01.xml)

[The TS class with the game character](https://dl.dropboxusercontent.com/u/17484152/Client.ts)

[and the error I get](https://dl.dropboxusercontent.com/u/17484152/Screen%20Shot%202016-09-19%20at%2020.07.37.png)

**Comment by SBCGames** [comment]
Hi enriqueto,

 Generally, it is important to match image name in atlas with image name in animation. In your last file, names in atlas are like this: 
client_01__0000_CARA
 and names in animation are like this:
client_01__0001_CARA.png

 By default animation names are stripped down to name only (client_01__0001_CARA) - or you can use new feature implemented on friday (as second parameter) to help you match it. Look into Test.ts in attached file:
```javascript
var spriterFile = new Spriter.SpriterXml(this.cache.getXML("TESTXml"), /* optional parameters */ { imageNameType: Spriter.eImageNameType.NAME_ONLY });
```
From this point it should work. I am attaching working project with your character:

[anim.zip](https://github.com/SBCGames/Spriter-Player-for-Phaser/files/480846/anim.zip)

 There is only one problem - there is missing image client_01__0011_MANGA-B in atlas, so it creates some unwanted effects in animation.

 Error you sent looks like your entity is not valid. Name of entity in animation is "cliente". Look into Test.ts file:
```javascript
this._spriterGroup = new Spriter.SpriterGroup(this.game, spriterData, "TEST", "cliente", 0, 100);
```
 Notice entity name as parameter and next parameter is anim name, which can be number or string.

 Let me know, if it works.

**Comment by enriqueto** [comment]
It works now!

Thanks for everything
