### ISSUE TITLE
Spriter group with fixed to camera true doesn't change position

### ISSUE THREAD

**Issue by Tembac** [SBCGames/Spriter-Player-for-Phaser#11]
Great tool so far!

I'm trying to make a spriter animation follow the camera. This is ussualy done setting fixedToCamera = true;

But If I set it to true for a sprite group it stays fixed on the top left corner of the camera and I can't change it's position.

I can get the same effect with the following code on update so probably something is missing from the SpriterGroup code that allows this:

```
  this.spriterGroup.position.setTo((this.game.camera.view.x + this.spriterDeviation.x) / this.game.camera.scale.x,
  (this.game.camera.view.y + this.spriterDeviation.y) / this.game.camera.scale.y);
```

**Comment by SBCGames** [comment]
Once you set fixedToCamera = true, you can change position of object only with object.cameraOffset. It is not related only to Spriter Player, but it is Phaser functionality.

**Comment by Tembac** [comment]
Ahh, Thanks for your answer! I was confused.
