### ISSUE TITLE
Blending Animations

### ISSUE THREAD

**Issue by relhtml** [SBCGames/Spriter-Player-for-Phaser#13]
This is awesome! Just wondering if there is there any options within the spriter player to perform blended animations? So from a run, slowing down into a walk, then halting to an idle animation? 

Thanks

**Comment by SBCGames** [comment]
Unfortunately not. You can only change speed of animation playback with setAnimationSpeedPercent() method (https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L179), but true blending is not there.
