### ISSUE TITLE
Trigger support

### ISSUE THREAD

**Issue by nefD** [SBCGames/Spriter-Player-for-Phaser#14]
Does this support triggers? If not, is it on the roadmap? If it is not on the roadmap, how difficult would it be to implement?

**Comment by SBCGames** [comment]
Currently these signals are supported (https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L10):

 - onSound
 - onEvent (= trigger),
 - onTagChange,
 - onVariableSet

 (onSound is in fact the same as onEvent and it is up to you to implement playing it)
