### ISSUE TITLE
Error with instant curve type name

### ISSUE THREAD

**Issue by Asyoues** [SBCGames/Spriter-Player-for-Phaser#17]
Hi,

spriter throw  an error with instant curves. I've found a mistake with the constant spelling:
"instatnt": 1 /* INSTANT */,

instead of: 
"instant": 1 /* INSTANT */,

Regards

**Comment by SBCGames** [comment]
Hi,
 this issue was fixed in this commit https://github.com/SBCGames/Spriter-Player-for-Phaser/commit/08b603b44e151b9542c195a15eff921a88d58dcb

 Please, load latest version - it should solve your problem.

**Comment by Asyoues** [comment]
Thank you!
