### ISSUE TITLE
box2d integration

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#18]
Hi, is it possible to attach box2d bodies to the sprites that compose the animation?

Although is not the optimal way to move box2d bodies I would set their positions according the coordinates and angle of the sprites.

What do you think?

**Comment by SBCGames** [comment]
Hi, moving box2D bodies is OK as far as it is set to kinematic. Now, question is where to move it and how to rotate it...

 I did small change here: https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L327
 Player can handle boxes and points attached to animation in Spriter editor. Unfortunatelly, when commenting out debug, I commented out one more line, so boxes and points were not processed - it is now fixed.

 If you add frames "DebugPoint" and "DebugBox" into your animation and uncomment blocks at:
- https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L330
- https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L416
 you should be able to see these objects on screen.

 For integration: it will need small tweak from your side. In updateCharacter method (https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L399) you can check type of object and identify it with object.name. In object.transformed, you get all information about position, scale and angle. So, it would be best to add some kind of callback if updateCharacter() just processed object of type BOX or POINT.

**Comment by SBCGames** [comment]
Ok, just added two new signals: onBoxUpdated and onPointUpdated. Both sends SpriterGroup and SpriterObject. You can register to them and get information needed to update your box2D objects.

**Comment by enriqueto** [comment]
thanks! I'll try this out

**Comment by SBCGames** [comment]
@enriqueto - please download latest version. I did some changes to work better with POINT and BOX. Test example was changed to show working with POINT.
