### ISSUE TITLE
Charmap pivot issue

### ISSUE THREAD

**Issue by Secretmapper** [SBCGames/Spriter-Player-for-Phaser#20]
When a charmap is pushed, and a texture in it uses another pivot, the animation still uses the 'old' pivot.

**Comment by SBCGames** [comment]
This is how currently Spriter works. Replacement images in charmaps need to have pivot point in the same position.

 Look for example here:  https://brashmonkey.com/forum/index.php?/topic/4139-character-map-possible-bug/
 or here: https://brashmonkey.com/forum/index.php?/topic/4013-need-help-with-character-maps/

 When using charmaps, Spriter uses original animation, including pivots and all other properties and in the very end it just replaces sprite image for image in topmost charmap.

**Comment by Secretmapper** [comment]
That's weird, I did set the pivot points - is it because the replacement image needs to be the same size as well? I set the pivot for my replacement image, but the pivot is different in my case because I'm using a differently sized image.
