### ISSUE TITLE
Tag Arrays?

### ISSUE THREAD

**Issue by Secretmapper** [SBCGames/Spriter-Player-for-Phaser#21]
Tags are most useful as a way to track the 'state/tag' of an animation. For example, a 'Guarding' Animation would have different states/tags: 'Vulnerable' (putting the shield up/down) and 'Invulnerable' (when the shield is up)

Currently the only way it seems to track tags is through events - this is problematic as it does not track what tags are currently active for the last keyframe up to now. Even more so it doesn't seem to be possible track this through the current API since the last tag is removed.

The spriter API here (https://github.com/flyover/spriter.js) seems to support it.

**Comment by SBCGames** [comment]
For tag queries, you can use:
 ```SpriterGroup.isTagOn(tagName: string): boolean```
 (https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L150)
 ```SpriterGroup.isTagOnById(tagId: number): boolean```
https://github.com/SBCGames/Spriter-Player-for-Phaser/blob/master/Spriter/src/Spriter/SpriterGroup.ts#L155

 Is it what you need?

**Comment by Secretmapper** [comment]
That was fast thanks! Looks like exactly what I'm looking for!
