### ISSUE TITLE
Crossfading support?

### ISSUE THREAD

**Issue by NeoHoffa** [SBCGames/Spriter-Player-for-Phaser#23]
Is Spriter-Player-for-Phaser able to transition or crossfade between animations like Phaser-Spine does? If not, what would be the scope of work to implement? 

https://github.com/orange-games/phaser-spine#crossfading-animations

Thanks!

**Comment by SBCGames** [comment]
Currently crossfading is not supported. Scope of work would be rather large with current code - it would need to split somehow animation processing from its visual representation, so two animations are procesed and then blended. To be honest, I do not know how to handle situations where one animation does not exactly match second one (some bone or spirte is added or missing).
