### ISSUE TITLE
"Cannot set frameName" when importing Spriter exported spritesheet

### ISSUE THREAD

**Issue by eyeswideopen** [SBCGames/Spriter-Player-for-Phaser#24]
When you import the atlas and scon files which were exported by Spriter i always encounter the mentioned error and the frames aren't loaded.

I tried the example files with the given code, which work fine. 
Using `load.atlasJSONHash` function since spriter always exports in that format doesn't help either nor does using XML.

Attached are the files of the used animation
[testAnimation.zip](https://github.com/SBCGames/Spriter-Player-for-Phaser/files/1069455/testAnimation.zip)

**Update:**
The above mentioned error was due to Spriter outputing frame names like: `"hero_graphics/forearm.png"` which both contains the folder and filetype extension.

My only solution now is to manually strip away the folder and adding `{ imageNameType: Spriter.eImageNameType.NAME_AND_EXTENSION}` to the `new Spriter.SpriterJSON()` call.

**What is still buggy:**
As Phaser doesn't support rotated frames i am forced to do the actual packing with TexturePacker since Spriter doesn't allow to prevent rotation.

Is there any other workaround?

**Comment by SBCGames** [comment]
Important thing is to match frame names between your atlas and animation. It is ok in your files. Your names look like "hero_graphics/foot_l.png" - i has path and extension.

eImageNameType is what you are looking for. It has four values:
  NAME_ONLY (default), => "foot_l"
  NAME_AND_EXTENSION, => "foot_l.png"
  FULL_PATH_NO_EXTENSION, => "hero_graphics/foot_l"
  ORIGINAL => "hero_graphics/foot_l.png"

So, you can use ORIGINAL and it should work.


Support for rotated atlas frames was introduced in 2.7.0 - https://github.com/photonstorm/phaser-ce/blob/master/CHANGELOG.md#version-270---worlds-end---22nd-november-2016

**Comment by eyeswideopen** [comment]
the ORIGINAL solved both! thanks for your help and the awesome player ;) saves me a lot of headache
