### ISSUE TITLE
phaser 3 compatibility

### ISSUE THREAD

**Issue by mickeyren** [SBCGames/Spriter-Player-for-Phaser#26]
hi @SBCGames 👋 

I'm wondering if you had any chance to test your spriter player with Phaser 3 and if so how was it?

**Comment by SBCGames** [comment]
Hi, not yet. But I am almost sure it will not work out of the box right now. On the other side, I do not think that it will need drastic changes to make it work - it will have to adapt to new sprites, groups and signals or their equivalents. I have no experience with Phaser 3 yet, but I am looking forward to study it :-)

**Comment by SBCGames** [comment]
Phaser 3 version will be separate from this one. I will create it when Phaser 3 supports unlimited nested containers.
