### ISSUE TITLE
"rotated" property issue in Phaser 2.6.2

### ISSUE THREAD

**Issue by redsanso** [SBCGames/Spriter-Player-for-Phaser#30]
Hello, 
I have an issue while trying to make my spritesheet animations work.
In my spritesheet atlas json file, some frames are rotated.
The spriter player seems to ignore the "rotated" property: the animation works, but most of the frames in the rendered sprite are not counter-rotated.
This results in the sprite looking disassembled.

Can you help me?

**Comment by SBCGames** [comment]
Hi,
 it looks like rotated sprites support was added to Phaser in version 2.7.0 - look at this link: [https://phaser.io/tutorials/advanced-rendering-tutorial/part7](url)

**Comment by redsanso** [comment]
Hi, 
no, we use Phaser 2.6.2 (before CE) and it actually supports rotated property in frames.

**Comment by redsanso** [comment]
Ok. I've been searching informations about this for days, still have no clue: it looks like the Spriter editor (i'll contact the team) doesn't allow you to manage all the atlas exporting properties. The result is that the only way to have a chance to export an atlas where all my frames are not rotated are very low, and this can only be achieved by tuning the spritesheet width/height and the padding, but this happens in 30% of the files, the rest is useless since most of the frames in the atlas are rotated

**Comment by SBCGames** [comment]
1) I am almost sure, that in time of writing Spriter Player for Phaser rotated frames were not suported. Support for this started later,
2) I never used Spriter packer, so I have no experience with it. You can pack your images in any other packer.
