### ISSUE TITLE
A question about an old article you posted

### ISSUE THREAD

**Issue by axmad22** [SBCGames/Spriter-Player-for-Phaser#31]
Hi did not know how to contact you but this way am not sure if this article I read is yours
[ Phaser tutorial: manage different screen sizes ](http://sbcgamesdev.blogspot.com/2015/04/phaser-tutorial-manage-different-screen.html)
Its a nice article thank you for it but the source to the project files link is broken if you still have the code and with the new Phasor do you still use this method as in the article to manage scaling. Am new to Phasor trying to learn it I just don't understand how they manage scaling on different devices without  black belts, and stretching  any help would be appreciated thanks

**Comment by SBCGames** [comment]
Hi, yes, the article was written be me.

To get whole source of utility, you can just copy all pieces of code starting from "ScreenUtils" heading - there is complete code.

 Ideas in article are still valid. But it works best with single screen games (no scrolling). You should first look at your game and choose right scaling strategy. Scaling strategy depends on type of your game.
 If you are starting with Phaser, then check scale modes: https://phaser.io/docs/2.6.2/Phaser.ScaleManager.html#scaleMode - this link, as well as code in article are for Phaser 2.
