### ISSUE TITLE
Phaser 2.19.2

### ISSUE THREAD

**Issue by EnigmaGun** [SBCGames/Spriter-Player-for-Phaser#33]
Thank you for this great project, unfortunately Spriter Player does not work properly for the current Phaser CE release anymore.
If I try the demo all body parts are on the same position and do not move. It seems as if the information about the parent (bone) has been lost.
I had a look into the code but I could not fix the issue.
Is there any change to get this fixed?

**Comment by SBCGames** [comment]
Please, check latest version. The issue should be solved.

**Comment by EnigmaGun** [comment]
Looks great, thank you very much for fixing it and the fast response!
