### ISSUE TITLE
support easings 

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#5]
support easing in and outs

**Comment by SBCGames** [comment]
Sorry, but I have no idea what it means :confused: Could you please specify your request? Easing of what?

**Comment by enriqueto** [comment]
I mean to support this kind of transitions between 2 positions. At the moment all movements are linear.
![easings-spriter](https://cloud.githubusercontent.com/assets/5557196/13457645/8242425e-e069-11e5-8ad9-ba871d683d15.png)

**Comment by SBCGames** [comment]
Oh, I see. Currently, these easing types are supported (see SpriterBone.ts):
 - instant,
 - linear,
 - 1d curve - quadratic,
 - 1d curve - cubic

 Other easing types will be supported in future.

**Comment by SBCGames** [comment]
rest of easing functions added
