### ISSUE TITLE
Mobile Performance

### ISSUE THREAD

**Issue by Tembac** [SBCGames/Spriter-Player-for-Phaser#7]
Thanks for this great tool!

I was testing it to use it on mobile but the performance seems to be very bad yet. Phaser render mode was webgl and I tested with the demo included here.

I tested it on a Nexus 6p using Crome and the framerate reaches 50fps.
On Iphone 6s with Safari it reaches 36fps.

These are the best devices on mobile so I didn't tested on lower devices yet. I suppose it will be slower.

 Is there anything we can do to improve it?

**Comment by SBCGames** [comment]
Hi, if the demo you tested was that guy shouting "Phaser! Phaser!", then reason for performance penalty is, that text is in fact rendered as debug text. And all debug drawing is decreasing performance a lot. Try to remove it from code and test on device again.

**Comment by Tembac** [comment]
Thanks for the quick answer. But it didn't improved much. I'm using debug text on other phaser games and the framerate is still 60fps.

**Comment by SBCGames** [comment]
Hmmm... how do you measure FPS? Another use of debug text? Try switching to Canvas renderer.
I am using the player in various games and without performance problems. In fact, all it does is series of (mostly linear) interpolations.

 You can also send me your test project (including your FPS measuring code in it) so I can look at it (can test on iPad).

**Comment by Tembac** [comment]
The only thing that I changed from your demo is adding to the render function this code to see the fps:

this.game.debug.text(this.game.time.fps, 32, 32);

And on the create of the preloader the following so the fps doesn't always show 0:

this.game.time.advancedTiming = true;

Do you know if there is any other way to measure framerate without using text?

Testing it with canvas renderer it reaches 60fps on the nexus 6p. I can't test it on iOs now. The problem is that the game where I'm going to use this needs webgl because we have some graphic effects that don't work under canvas :(

**Comment by SBCGames** [comment]
If you get 60 fps with canvas renderer, then reason for poor performace is debug text - it has to upload texture to GPU on every frame! So, it does not matter, wherther you print one character or many.

 Get rid of all debug texts and if you need soume text output with WebGL renderer (and you need high performance in the same time), then use bitmap text.

**Comment by Tembac** [comment]
Thanks for your advice. Do you know a better way to get fps on webgl? 

I'll look on the forums also.

Thanks for your help!

**Comment by SBCGames** [comment]
Way you get FPS is OK. Just print it with bitmap font.
