### ISSUE TITLE
it does work with the latest version of spriter

### ISSUE THREAD

**Issue by enriqueto** [SBCGames/Spriter-Player-for-Phaser#9]
We are using the latest version of spriter (v9) and it doesn't work. They may have changed something in the json that stores the animation.

The character has 3 states: "idle", "happy" and "disappointed"

Here the files I use:

[animation json](https://dl.dropboxusercontent.com/u/17484152/cliente_01_.json)
[texture altas png](https://dl.dropboxusercontent.com/u/17484152/spritesheet_cliente01.png)
[texture atlas json](https://dl.dropboxusercontent.com/u/17484152/spritesheet_cliente01.json)

**Comment by SBCGames** [comment]
We are using R9 with .xml and it works. I will check if there is some change in .json. Any chance you sent me also source animation (in case bug is elswhere)?

**Comment by enriqueto** [comment]
[animation](https://dl.dropboxusercontent.com/u/17484152/cliente%201-%203%20animaciones.zip)

**Comment by enriqueto** [comment]
sorry he uses these files:
[client](https://dl.dropboxusercontent.com/u/17484152/client%20test.zip)

**Comment by SBCGames** [comment]
Ok, then things are more clear. I spent some time with it and:
 - Phaser does not support rotated images in atlas. Most of them is rotated in your atlas - switch it off in TexturePacker,
 - path stored for individual images in your atlas is "miembros/image_name.png". Spriter Player currently strips out everything but image_name. I do not use Texture Packer as I have my own tool with additional special features :smile: , but I know, it is possible to instruct TP to not include file extension. I am not sure, if it is possible also to force it to not add path. If not, then just move images one folder up where Spriter animation resides.

Please, try and let me know.

**Comment by SBCGames** [comment]
Look at "news". I added possibility to set type of image names in optional parameters in Spriter.SpriterJSON when loading animation. Only issue is now unsupported rotation of atlas images.
